[project]
name = "blockchain"
requirements = []
costs_version = 1
[contracts.MultiNft]
path = "contracts/MultiNft.clar"
depends_on = []

[contracts.NftCollection]
path = "contracts/NftCollection.clar"
depends_on = ["NftTrait"]

[contracts.NftTrait]
path = "contracts/NftTrait.clar"
depends_on = []
